dist/Makefile: Add cbuild-sdks target to download SDKs.

diff --git a/tools/cbuild b/tools/cbuild
--- a/tools/cbuild
+++ b/tools/cbuild
@@ -12,14 +12,16 @@ SCRIPT=build-$TIME
 ID=${SCRIPT}
 HDIR=/tmp
 CDIR=/tmp
-WSM=../workshop/mingw-build
-WSL=../workshop/linux-build
+SDK_DIR=dist/sdk
 
-if [ "$1" == "win" ]; then
-	if [ ! -d ${WSM} ]; then
-		echo "Library archive ${WSM} not found!"
-		exit
-	fi
+if [ ! -d ${SDK_DIR} ]; then
+	echo "Library archive ${SDK_DIR} not found!"
+	echo "Run \"make -C dist cbuild-sdks\""
+	exit
+fi
+
+case $1 in
+windows)
 	echo '
   unzip /tmp/allegro-x86_64-w64-mingw32-gcc-10.2.0-posix-seh-static-5.2.7.0.zip
   mv allegro usr
@@ -31,8 +33,8 @@ if [ "$1" == "win" ]; then
 ' >$HDIR/${SCRIPT}
 
 	podman run -d -it --name=$ID xu4/f33-mingw:1.0 /bin/bash || exit
-	podman cp ${WSM}/allegro-x86_64-w64-mingw32-gcc-10.2.0-posix-seh-static-5.2.7.0.zip $ID:$CDIR
-	podman cp ${WSM}/boron-x86_64-w64-mingw32-static-2.0.6.zip $ID:$CDIR
+	podman cp ${SDK_DIR}/allegro-x86_64-w64-mingw32-gcc-10.2.0-posix-seh-static-5.2.7.0.zip $ID:$CDIR
+	podman cp ${SDK_DIR}/boron-x86_64-w64-mingw32-static-2.0.6.zip $ID:$CDIR
 	podman cp project.tar.gz $ID:$CDIR
 	podman cp $HDIR/${SCRIPT} $ID:$CDIR/${SCRIPT}
 	podman exec -it -u build $ID /bin/bash $CDIR/${SCRIPT}
@@ -41,12 +43,14 @@ if [ "$1" == "win" ]; then
 	# Build zip archive.
 	if [ "$2" != "-b" ]; then
 		mkdir -p /tmp/xu4
-		FN=`readlink -f ${WSM}/allegro-dll.tar.bz2`
+		FN=`readlink -f ${SDK_DIR}/allegro-dll.tar.bz2`
 		tar xf $FN -C /tmp/xu4
 		cp /tmp/u4.exe-$TIME /tmp/xu4/u4.exe
 		cd /tmp; zip -r xu4-win32.zip xu4
 	fi
-else
+	;;
+
+linux)
 	echo '
   tar xjf /tmp/boron-x86_64-static-2.0.6.tar.bz2
   mkdir u4
@@ -56,12 +60,19 @@ else
 ' >$HDIR/${SCRIPT}
 
 	podman run -d -it --name=$ID xu4/f33-gcc:1.0 /bin/bash || exit
-	podman cp ${WSL}/boron-x86_64-static-2.0.6.tar.bz2 $ID:$CDIR
+	podman cp ${SDK_DIR}/boron-x86_64-static-2.0.6.tar.bz2 $ID:$CDIR
 	podman cp project.tar.gz $ID:$CDIR
 	podman cp $HDIR/${SCRIPT} $ID:$CDIR/${SCRIPT}
 	podman exec -it $ID /bin/bash $CDIR/${SCRIPT}
 	podman cp $ID:/home/build/u4/u4 /tmp/u4-$TIME
-fi
+	;;
+
+*)
+	echo "Usage: $0 {linux|windows} [-b]"
+	echo -e '\nOptions:'
+	echo '  -b    Build binary only; do not create archive.'
+	exit 1
+esac
 
 echo "$SCRIPT done!"
 podman stop $ID
